# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
  . ~/.bashrc
fi

#cursor shows current branch
function parse_git_branch {
  ref=$(git symbolic-ref HEAD 2> /dev/null) || return
  echo "("${ref#refs/heads/}")"
}
export PS1="[\u@\h \W]\$(parse_git_branch)\$ "

# User specific environment and startup programs

PATH=$PATH:$HOME/bin

export PATH

eval "$(rbenv init -)"
